spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: trace
          uri: http://localhost:8080
          predicates:
            - Path=/trace
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
server:
  port: 7070